HomePageUrl =http://10.1.30.233:5000/Home/Index

QA.url=http://10.1.30.233:5000/Account/Login
Dev.url=http://10.1.30.200:5000/Account/Login
Staging.url=http://10.1.30.210:5000/Account/Login

# Local , Remote , Headless #
executionType=Local
# Chrome , Firefox , Edge , #
browserType=Chrome